#!/bin/sh

# Rerun 'dmenu_path' (reconstructing the cache in '~/.dmenu_cache')
# whenever a file is removed or added to a directory in 'PATH'.  Start
# this in the background and enjoy.  Requires inotify-tools for
# 'inotifywait'.

(IFS=":"; inotifywait -q -e move -e create -e delete $PATH -m) \
| while read line; do dmenu_path > /dev/null; done
