#!/bin/sh
#
# Upload a single file to a server and make it readable, echoing the
# URL at which it is now available.  This is convenient if default
# umask settings make just SCPing create an inaccessible file.

server=sigkill.dk
httproot=/var/www/htdocs/sigkill.dk
dir=junk
src=$(echo "$@" | sed 's!/$!!')

set -e
set -x
rsync -uzPr --chmod=F644,D755 "$src" "$server:$httproot/$dir/"
echo "http://$server/$dir/$(basename "$1")"
